[tool.poetry]
name = "portfolio-website"
version = "0.1.0"
description = ""
authors = ["BalajiKesavan <36139209+balajikesavan90@users.noreply.github.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.44.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
