[theme]
base="light"
primaryColor="#0070c0" # light blue
backgroundColor="#e6e6f7"
secondaryBackgroundColor="#F3F3F3" #offwhite
textColor="black"
font="sans serif"

[client]
showSidebarNavigation = false